# Generated by Django 3.1 on 2020-08-24 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('authors', models.ManyToManyField(related_name='books', to='lib.Author', verbose_name='авторы')),
            ],
        ),
        migrations.CreateModel(
            name='BookShelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='код')),
            ],
        ),
        migrations.CreateModel(
            name='BookPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveIntegerField(verbose_name='место')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='lib.book', verbose_name='книга')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='lib.bookshelf', verbose_name='полка')),
            ],
            options={
                'ordering': ('place',),
                'unique_together': {('shelf', 'place')},
            },
        ),
    ]
